version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/recollection
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECRET_KEY
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  db:
    image: library/postgres:13-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: