# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:45
from __future__ import unicode_literals

import apps.words.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('words', '0001_initial'), ('words', '0002_auto_20160917_0358'), ('words', '0003_auto_20160917_2010'), ('words', '0004_japaneseword_created_at'), ('words', '0005_auto_20160917_2022'), ('words', '0006_auto_20160917_2028'), ('words', '0007_auto_20160917_2351'), ('words', '0008_auto_20160917_2355'), ('words', '0009_auto_20160918_2248'), ('words', '0010_auto_20160919_0308')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
            options={
                'verbose_name': 'Japanese Word',
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, verbose_name='Kanji')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(blank=True, max_length=100, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji Reading')),
                ('hiragana', models.CharField(blank=True, max_length=50, validators=[apps.words.validators.validate_hiragana_char], verbose_name='Hiragana Reading')),
                ('katakana', models.CharField(blank=True, max_length=50, validators=[apps.words.validators.validate_katakana_char], verbose_name='Katakana Reading')),
                ('default_display', models.IntegerField(choices=[(1, 'Romaji'), (2, 'Hiragana'), (3, 'Katakana')], default=1, verbose_name='Default Display')),
            ],
        ),
        migrations.AddField(
            model_name='kanji',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='kanjis_reading', to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='kanjis',
            field=models.ManyToManyField(blank=True, related_name='words', to='words.Kanji', verbose_name='Kanjis'),
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='words_reading', to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='english_words_reading', to='words.Reading', verbose_name='Reading'),
        ),
        migrations.AlterModelOptions(
            name='englishword',
            options={'verbose_name': 'English Word'},
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date'),
        ),
        migrations.RemoveField(
            model_name='englishword',
            name='reading',
        ),
        migrations.AddField(
            model_name='englishword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishword',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='english_words_readings', to='words.Reading', verbose_name='Reading'),
        ),
        migrations.CreateModel(
            name='JapaneseSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(db_index=True, max_length=3, unique=True, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji')),
                ('hiragana', models.CharField(db_index=True, max_length=2, validators=[apps.words.validators.validate_hiragana_char], verbose_name='Hiragana')),
                ('katakana', models.CharField(db_index=True, max_length=2, validators=[apps.words.validators.validate_katakana_char], verbose_name='Katakana')),
            ],
        ),
        migrations.AlterField(
            model_name='englishword',
            name='word',
            field=models.CharField(max_length=100, validators=[apps.words.validators.validate_eng_char], verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='word',
            field=models.CharField(max_length=100, validators=[apps.words.validators.validate_jap_char], verbose_name='Word'),
        ),
    ]
