# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:47
from __future__ import unicode_literals

from django.db import migrations, models

import apps.words.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, validators=[apps.words.validators.validate_eng_char], verbose_name='Word')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'English Word',
            },
        ),
        migrations.CreateModel(
            name='JapaneseSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(db_index=True, max_length=3, unique=True, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji')),
                ('hiragana', models.CharField(db_index=True, max_length=2, validators=[apps.words.validators.validate_hiragana_char], verbose_name='Hiragana')),
                ('katakana', models.CharField(db_index=True, max_length=2, validators=[apps.words.validators.validate_katakana_char], verbose_name='Katakana')),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, validators=[apps.words.validators.validate_jap_char], verbose_name='Word')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Japanese Word',
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, verbose_name='Kanji')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(blank=True, max_length=100, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji Reading')),
                ('hiragana', models.CharField(blank=True, max_length=50, validators=[apps.words.validators.validate_hiragana_char], verbose_name='Hiragana Reading')),
                ('katakana', models.CharField(blank=True, max_length=50, validators=[apps.words.validators.validate_katakana_char], verbose_name='Katakana Reading')),
                ('default_display', models.IntegerField(choices=[(1, 'Romaji'), (2, 'Hiragana'), (3, 'Katakana')], default=1, verbose_name='Default Display')),
            ],
        ),
        migrations.AddField(
            model_name='kanji',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='kanjis_reading', to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='kanjis',
            field=models.ManyToManyField(blank=True, related_name='words', to='words.Kanji', verbose_name='Kanjis'),
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='words_reading', to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='english_words_readings', to='words.Reading', verbose_name='Reading'),
        ),
    ]
