# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
            options={
                'verbose_name': 'Japanese Word',
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, verbose_name='Kanji')),
                ('meaning', models.TextField(blank=True, max_length=500, verbose_name='Meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(blank=True, max_length=100, verbose_name='Romaji Reading')),
                ('hiragana', models.CharField(blank=True, max_length=50, verbose_name='Hiragana Reading')),
                ('katakana', models.CharField(blank=True, max_length=50, verbose_name='Katakana Reading')),
            ],
        ),
        migrations.AddField(
            model_name='kanji',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='kanjis_reading', to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='kanjis',
            field=models.ManyToManyField(related_name='words', to='words.Kanji', verbose_name='Kanjis'),
        ),
        migrations.AddField(
            model_name='japaneseword',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='words_reading', to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='english_words_reading', to='words.Reading', verbose_name='Reading'),
        ),
    ]
