# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models

import apps.words.validators


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='hiragana',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                validators=[
                    apps.words.validators.validate_hiragana_char],
                verbose_name='Hiragana Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='katakana',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                validators=[
                    apps.words.validators.validate_katakana_char],
                verbose_name='Katakana Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='romaji',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                validators=[
                    apps.words.validators.validate_eng_char],
                verbose_name='Romaji Reading'),
        ),
    ]
