# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20160917_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='japaneseword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
