# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models

import apps.words.validators


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20161001_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='eng_words_tags',
                to='words.SearchTag',
                verbose_name='Search Tags'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='jap_words_tags',
                to='words.SearchTag',
                verbose_name='Search Tags'),
        ),
        migrations.AlterField(
            model_name='searchtag',
            name='eng_tag',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                validators=[
                    apps.words.validators.validate_eng_char],
                verbose_name='English Tag'),
        ),
        migrations.AlterField(
            model_name='searchtag',
            name='jap_tag',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=25,
                validators=[
                    apps.words.validators.validate_jap_char],
                verbose_name='Japanese Tag'),
        ),
    ]
