# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20160917_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='reading',
        ),
        migrations.AddField(
            model_name='englishword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishword',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='english_words_readings', to='words.Reading', verbose_name='Reading'),
        ),
    ]
