# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20161002_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='meaning',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Meaning'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='meaning',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Meaning'),
        ),
    ]
