# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 00:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20161015_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='readings',
            field=models.ManyToManyField(blank=True, to='words.Reading', verbose_name='Reading'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='tags',
            field=models.ManyToManyField(blank=True, to='words.SearchTag', verbose_name='Search Tags'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='kanjis',
            field=models.ManyToManyField(blank=True, to='words.Kanji', verbose_name='Kanjis'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='readings',
            field=models.ManyToManyField(blank=True, to='words.Reading', verbose_name='Readings'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='tags',
            field=models.ManyToManyField(blank=True, to='words.SearchTag', verbose_name='Search Tags'),
        ),
    ]
