# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_auto_20161016_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='default_display',
            field=models.IntegerField(
                choices=[
                    (1,
                     'Romaji'),
                    (2,
                     'Hiragana'),
                    (3,
                     'Katakana')],
                default=2,
                verbose_name='Default Display'),
        ),
    ]
