# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:48
from __future__ import unicode_literals

import apps.words.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_auto_20160917_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(db_index=True, max_length=3, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji')),
                ('hiragana', models.CharField(db_index=True, max_length=2, validators=[apps.words.validators.validate_hiragana_char], verbose_name='Hiragana')),
                ('katakana', models.CharField(db_index=True, max_length=2, validators=[apps.words.validators.validate_katakana_char], verbose_name='Katakana')),
            ],
        ),
        migrations.AlterField(
            model_name='englishword',
            name='word',
            field=models.CharField(max_length=100, validators=[apps.words.validators.validate_eng_char], verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='japaneseword',
            name='word',
            field=models.CharField(max_length=100, validators=[apps.words.validators.validate_jap_char], verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='hiragana',
            field=models.CharField(blank=True, max_length=50, validators=[apps.words.validators.validate_hiragana_char], verbose_name='Hiragana Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='katakana',
            field=models.CharField(blank=True, max_length=50, validators=[apps.words.validators.validate_katakana_char], verbose_name='Katakana Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='romaji',
            field=models.CharField(blank=True, max_length=100, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji Reading'),
        ),
    ]
