# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 03:08
from __future__ import unicode_literals

import apps.words.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_auto_20160918_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japanesesyllable',
            name='romaji',
            field=models.CharField(db_index=True, max_length=3, unique=True, validators=[apps.words.validators.validate_eng_char], verbose_name='Romaji'),
        ),
    ]
