# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0009_auto_20161016_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchtag',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
