# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0010_auto_20170223_0036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='englishword',
            unique_together=set([('owner', 'word')]),
        ),
        migrations.AlterUniqueTogether(
            name='japaneseword',
            unique_together=set([('owner', 'word')]),
        ),
        migrations.AlterUniqueTogether(
            name='kanji',
            unique_together=set([('owner', 'character')]),
        ),
        migrations.AlterUniqueTogether(
            name='searchtag',
            unique_together=set([('eng_tag', 'jap_tag', 'owner')]),
        ),
    ]
